### ISSUE TITLE
it seems to be wrong to judge whether the transaction exists

### ISSUE THREAD

**Issue by mingming-tang** [palaidn/palaidn_subnet#2]
https://github.com/palaidn/palaidn_subnet/blob/bb953f72ef4699265909e41b936e26b3c6c3ee2b/palaidn/utils/fraud_data.py#L68

if transactions did not exist, the 'exists' equal to (0, ), and bool((0, )) equal to True

**Comment by mingming-tang** [comment]
![img_v3_02dv_39357a92-a2f7-43c8-8f36-4dbc95b257eg](https://github.com/user-attachments/assets/ea97be93-10c4-4854-b233-8ece372147fd)

**Comment by mattgeomercury** [comment]
closed
